function replaceLineBreaks(inputString) {
  // Use a regular expression with the global flag to replace all occurrences
  var replacedString = inputString.replace(/\r\n/g, '<br>');

  return replacedString;
}

var newsArticle = `
 [**Federal cabinet approves restructuring of national carrier**](https://www.dawn.com/news/1811705/federal-cabinet-approves-restructuring-of-national-carrier)\r\n\r\n[The Dawn News - Home](https://www.dawn.com/) by none@none.com (Dawn.com) / Feb 7, 2024 at 1:06 AM//keep unread//hide\r\n\r\n  \r\n\r\nWith just two days to go for general elections, the federal cabinet on Tuesday approved the restructuring of the national flag carrier Pakistan International Airlines (PIA), state-run Radio Pakistan [reported](https://www.radio.gov.pk/06-02-2024/federal-cabinet-approves-restructuring-pia-privatization-of-fwbkl).\r\n\r\nThe development comes after the Election Commission of Pakistan (ECP) [asked](https://www.dawn.com/news/1811231) the government to “refrain from taking any further steps, including the signing of an agreement” about the privatization of PIA or its entities until its formal clearance.\r\n\r\nIn a letter to the cabinet secretary, the electoral watchdog had reminded the federal government of Article 230 of the Constitution, which explains the roles and limitations of the caretaker government and sought all relevant cabinet documentation, sources told Dawn.\r\n\r\nThe ECP had directed the government to “provide all relevant documents prepared for approval of the Cabinet containing a comprehensive privatization programme in relation to the privatization of PIA” to the ECP as required under Clause 5(b) of the Privatization Commission Ordinance, 2000, and Section 230 of the Constitution.\r\n\r\nAccording to Radio Pakistan, the federal cabinet — chaired by caretaker Prime Minister Anwaarul Haq Kakar in Islamabad today — consented to the appointment of a financial advisor for the financial and administrative reorganization of PIA.\r\n\r\n“The cabinet was informed that PIA will be bifurcated into two companies, namely TopCo and HoldCo. Basic engineering operations, ground handling, cargo, flight kitchen, and training will be attached to TopCo, while departments like PIA Investment, Precision Engineering Complex, and other subsidiaries as well as properties will be put under HoldCo,” the report said.\r\n\r\nIt highlighted that these measures would help attract investors towards PIA.\r\n\r\nMoreover, the cabinet also directed its sub-committee on privatization to dispose of matters related to state-owned entities’ claims of undecided amounts on the national flag carrier at the earliest, the report added.\r\n\r\nIn the past, elected governments have shied away from undertaking unpopular reforms, including the sale of the flag carrier. But Pakistan, in deep economic crisis, agreed in June to overhaul loss-making state-owned enterprises under a deal with the International Monetary Fund (IMF) for a [$3 billion bailout](https://www.dawn.com/news/1762360).
`;

var modifiedString = replaceLineBreaks(newsArticle);
console.log(modifiedString);
