# Generated by Django 4.2.9 on 2024-01-11 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=300, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "date_time",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=300, null=True)),
                ("last_name", models.CharField(blank=True, max_length=300, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone_no", models.CharField(blank=True, max_length=300, null=True)),
                ("education", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "passing_out_year",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "enroll_course",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
            ],
        ),
    ]
