# Generated by Django 4.2.9 on 2024-01-15 07:17

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.ImageField(upload_to="")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("technique_training", "Technique and Training"),
                            ("industry_news", "Industry News and Trends"),
                            ("safety_responsibility", "Safety and Responsibility"),
                            ("competition_coverage", "Competition Coverage"),
                            ("historical_perspectives", "Historical Perspectives"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("description", markdownx.models.MarkdownxField()),
            ],
        ),
    ]
