# Generated by Django 4.2.9 on 2024-01-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="enroll",
            name="resume",
            field=models.FileField(default=1, upload_to="resume_uploads/"),
            preserve_default=False,
        ),
    ]
