# Generated by Django 4.2.7 on 2024-02-07 05:46

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
